name: Snyk Scan
on: push
jobs:
 security:
    runs-on: ubuntu-latest
    env:
     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: snyk/actions/setup@master
    - name: Snyk test
      continue-on-error: true
      run: snyk test --all-projects
    - name: Snyk monitor
      run: snyk monitor --all-projects
